django/mysite/first/urls.py
from django.conf.urls import url,include
from first import views as first_views

urlpatterns = [
    url(r'^route/(?P<path>\w+)/$', first_views.route,name='route'),
    url(r'^edit/(?P<id>[0-9a-zA-Z\-]+)/$', first_views.edit,name='edit'),
    url(r'^addAction/$', first_views.addAction, name='addAction'),
    url(r'^deleteAction/(?P<id>[0-9a-zA-Z\-]+)$', first_views.deleteAction, name='deleteAction'),
    url(r'^editAction/(?P<id>[0-9a-zA-Z\-]+)$', first_views.editAction, name='editAction'),
    url(r'^returnJSONAction/$', first_views.returnJSONAction, name='returnJSONAction')
]

django/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^first/',include('first.urls',namespace='first')),
    url(r'^admin/', admin.site.urls),
]

django/mysite/first/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import uuid

# Create your models here.

@python_2_unicode_compatible
class Person(models.Model):
    id=models.UUIDField(primary_key=True, auto_created=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30)
    age = models.IntegerField()

django/mysite/first/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse
from django.db import connection,transaction


# Create your views here.

from django.shortcuts import render
from .models import Person
from django import forms


class personBO(forms.Form):
    id=forms.CharField()
    name = forms.CharField()
    age = forms.IntegerField()

def route(request, path):
    if path == 'index':
        rows=Person.objects.raw('select * from first_person')
        for row in rows:
            print(row.id)

        cursor=connection.cursor()
        cursor.execute("select * from first_person")
        rows=cursor.fetchall()
        for row in rows:
            print(row)

        persons = Person.objects.all()
        return render(request, 'index.html', {'persons': persons})
    elif path == 'add':
        bo = personBO()
        return render(request, 'add.html', {'bo': bo})

def edit(request,id):

    person = Person.objects.get(id=id)
    bo = personBO(
        initial={'id':id,'name': person.name, 'age': person.age}
    )
    return render(request, 'add.html', {'bo': bo})

def addAction(request):
    name = request.POST.get("name")
    age = request.POST.get("age")
    Person.objects.create(name=name, age=age)
    persons = Person.objects.all()
    return render(request, 'index.html', {'persons': persons})


def deleteAction(request, id):
    Person.objects.filter(id=id).delete()
    persons = Person.objects.all()
    return render(request, 'index.html', {'persons': persons})


def editAction(request,id):
    name1 = request.POST.get("name")
    age1 = request.POST.get("age")
    Person.objects.get(pk=id).update(name=name1,age=age1)
    persons = Person.objects.all()
    return render(request, 'index.html', {'persons': persons})

def returnJSONAction(request):
    jsonObject=serializers.serialize('json',Person.objects.all())
    return HttpResponse(jsonObject,content_type='application/json')

django/mysite/first/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'first:addAction' %}" method="post">
    {% csrf_token %}
    <div>
       <label>姓名：</label>{{bo.name}}
    </div>
    <div>
       <label>年龄：</label>{{bo.age}}
    </div>
    <div>
      <button type="submit">提交</button>
    </div>

</form>

</body>
</html>

django/mysite/first/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'first:editAction' {{bo.id}} %}" method="post">
    {% csrf_token %}
    <div>
       <label>姓名：</label>{{bo.name}}
    </div>
    <div>
       <label>年龄：</label>{{bo.age}}
    </div>
    <div>
      <button type="submit">提交</button>
    </div>

</form>

</body>
</html>

django/mysite/first/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>第一个python web例子</p>
<a href="/first/route/add/">新增</a>
<a>修改</a>
<table>
    {% for person in persons%}
    <tr>
        <td>{{person.id}}</td>
        <td>{{person.name}}</td>
        <td>{{person.age}}</td>
        <td><a href="/first/edit/{{person.id}}">修改</a></td>
        <td><a href="/first/deleteAction/{{person.id}}">删除</a></td>
    </tr>
    {% endfor %}
</table>
</body>
</html>